### PR TITLE
use monotonic clock

### LINKED ISSUE #22: Monotonic Time
If the computer's time changes, Date() will be affected, that's why a monotonic time should be used, such as process.hrtime.

### PR DESCRIPTION
**Pull request by srijs**
fixes #22

### CODE REVIEW

**Comment by jhurliman** [comment]
I like this change, but could `getMilliseconds` be made to work in the case where `process` or `process.hrtime` do not exist?

**Comment by eaaliprantis** [comment]
What about using Moment.js instead?

**Comment by jhurliman** [comment]
If anyone has interest in seeing this merged, can you modify the `getMilliseconds` method to fall back to `+new Date()` in the case of process or process.hrtime not being defined (i.e. browsers)?

**Comment by jhurliman** [comment]
Addressed by #44

**Pull request closed without merging**
